DataBase:
  Host: 111.231.164.113
  DataBase: echo-vben-admin
  Port: 3306
  User: echo-vben-admin
  Pass: echo_vben_admin
# 服务器配置
Server:
  Dev: true
  HttpPort: 3333
  WebSocketPath: /websocket
  GlobalPrefix: /api
Redis:
  Enable: false
  Addr: 111.231.164.113:6379
  Password: redis_FmXD4d
  DB: 4
Jwt:
  JwtKey: Jwt-JwtKey
  Expire: 86400
  MaxLoginFailCount: 5
# 日志配置
Logger:
  Level: INFO  # Level 最低日志等级，DEBUG<INFO<WARN<ERROR<FATAL 等级以上的日志才会写入日志文件
  LogFilePath: ./log/
  FileName: app.log # FileName 日志文件位置
  ErrorFileName: error.log # 错误日志配置
  MaxSize: 100    #  MaxSize 进行切割之前，日志文件的最大大小(MB为单位)，默认为100MB
  MaxAge: 30    #  MaxAge 是根据文件名中编码的时间戳保留旧日志文件的最大天数。
  MaxBackups:  30    #  MaxBackups 是要保留的旧日志文件的最大数量。默认是保留所有旧的日志文件（尽管 MaxAge 可能仍会导致它们被删除。）
# 离线IP定位库
Ip2RegionConfig:
  FilePath: ./ip2region.xdb
# 腾讯全家桶的配置
Tencent:
  #   企业微信的
  Qywx: 
    CorpId:
    CorpSecret:
    AgentId:
    RedirectionUrl:
  #  存储桶
  Cos:
    SecretId:
    SecretKey:
    AppId:
    Region:
    Bucket:
    CdnUrl: 
