// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/super-sunshines/echo-server-core/core"

const TableNameSysLogOperate = "sys_log_operate"

// SysLogOperate mapped from table <sys_log_operate>
type SysLogOperate struct {
	ID              int64     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	Title           string    `gorm:"column:title;type:varchar(255);comment:标题" json:"title"`                        // 标题
	BusinessType    int64     `gorm:"column:business_type;type:int(2);comment:业务类型" json:"businessType"`             // 业务类型
	CallFunc        string    `gorm:"column:call_func;type:varchar(255);comment:执行的方法" json:"callFunc"`              // 执行的方法
	RequestMethod   string    `gorm:"column:request_method;type:varchar(255);comment:请求方法" json:"requestMethod"`     // 请求方法
	OperateUserID   int64     `gorm:"column:operate_user_id;type:int(11);comment:操作者ID" json:"operateUserId"`        // 操作者ID
	OperateType     int64     `gorm:"column:operate_type;type:int(11);comment:操作类型" json:"operateType"`              // 操作类型
	OperateName     string    `gorm:"column:operate_name;type:varchar(255);comment:操作人员" json:"operateName"`         // 操作人员
	OperateDepart   string    `gorm:"column:operate_depart;type:varchar(255);comment:部门名称" json:"operateDepart"`     // 部门名称
	OperateURL      string    `gorm:"column:operate_url;type:varchar(255);comment:请求地址" json:"operateUrl"`           // 请求地址
	OperateIP       string    `gorm:"column:operate_ip;type:varchar(255);comment:请求IP" json:"operateIp"`             // 请求IP
	OperateLocation string    `gorm:"column:operate_location;type:varchar(255);comment:请求地点" json:"operateLocation"` // 请求地点
	OperateParam    string    `gorm:"column:operate_param;type:text;comment:请求参数" json:"operateParam"`               // 请求参数
	RequestJSONBody string    `gorm:"column:request_json_body;type:text;comment:请求体" json:"requestJsonBody"`         // 请求体
	JSONResult      string    `gorm:"column:json_result;type:text;comment:返回响应" json:"jsonResult"`                   // 返回响应
	ErrorMsg        string    `gorm:"column:error_msg;type:text;comment:错误信息" json:"errorMsg"`                       // 错误信息
	Status          int64     `gorm:"column:status;type:int(1);comment:操作状态" json:"status"`                          // 操作状态
	OperateTime     core.Time `gorm:"column:operate_time;type:datetime;comment:操作时间" json:"operateTime"`             // 操作时间
	CostTime        int64     `gorm:"column:cost_time;type:int(11);comment:消耗时间" json:"costTime"`                    // 消耗时间
}

// TableName SysLogOperate's table name
func (*SysLogOperate) TableName() string {
	return TableNameSysLogOperate
}
