// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/super-sunshines/echo-server-core/core"
	"gorm.io/gorm"
)

const TableNameSysUserDepartment = "sys_user_department"

// SysUserDepartment 用户部门表
type SysUserDepartment struct {
	ID           int64          `gorm:"column:id;type:int(255);primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	UserID       int64          `gorm:"column:user_id;type:int(255);comment:用户ID" json:"userId"`                        // 用户ID
	DepartmentID string         `gorm:"column:department_id;type:varchar(500);comment:部门ID" json:"departmentId"`        // 部门ID
	Role         string         `gorm:"column:role;type:varchar(500);comment:部门中角色(未使用)" json:"role"`                   // 部门中角色(未使用)
	CreateDept   int64          `gorm:"column:create_dept;type:int(11);comment:创建部门" json:"createDept"`                 // 创建部门
	CreateBy     int64          `gorm:"column:create_by;type:int(11);comment:创建者" json:"createBy"`                      // 创建者
	CreateTime   core.Time      `gorm:"column:create_time;autoCreateTime;type:datetime;comment:创建时间" json:"createTime"` // 创建时间
	UpdateBy     int64          `gorm:"column:update_by;type:int(11);comment:更新者" json:"updateBy"`                      // 更新者
	UpdateTime   core.Time      `gorm:"column:update_time;autoUpdateTime;type:datetime;comment:更新时间" json:"updateTime"` // 更新时间
	DeleteTime   gorm.DeletedAt `gorm:"column:delete_time;type:datetime;comment:删除时间" json:"deleteTime"`                // 删除时间
}

// TableName SysUserDepartment's table name
func (*SysUserDepartment) TableName() string {
	return TableNameSysUserDepartment
}
