// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/super-sunshines/echo-server-core/core"
	"gorm.io/gorm"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID             int64             `gorm:"column:id;type:int(255);primaryKey;autoIncrement:true;comment:主键" json:"id"`      // 主键
	Code           string            `gorm:"column:code;type:varchar(255);comment:权限代码" json:"code"`                          // 权限代码
	Name           string            `gorm:"column:name;type:varchar(255);comment:角色名称" json:"name"`                          // 角色名称
	Description    string            `gorm:"column:description;type:varchar(500);comment:权限描述" json:"description"`            // 权限描述
	MenuIDList     core.Array[int64] `gorm:"column:menu_id_list;type:json;comment:目录列表" json:"menuIdList"`                    // 目录列表
	HomePath       string            `gorm:"column:home_path;type:varchar(255);comment:主页目录" json:"homePath"`                 // 主页目录
	QueryStrategy  int64             `gorm:"column:query_strategy;type:int(1);default:1;comment:查询策略" json:"queryStrategy"`   // 查询策略
	UpdateStrategy int64             `gorm:"column:update_strategy;type:int(1);default:1;comment:更新策略" json:"updateStrategy"` // 更新策略
	Enable         core.IntBool      `gorm:"column:enable;type:int(1);comment:启用状态" json:"enable"`                            // 启用状态
	CreateDept     int64             `gorm:"column:create_dept;type:int(255);comment:创建部门" json:"createDept"`                 // 创建部门
	CreateBy       int64             `gorm:"column:create_by;type:int(255);comment:创建者" json:"createBy"`                      // 创建者
	CreateTime     core.Time         `gorm:"column:create_time;autoCreateTime;type:datetime;comment:创建时间" json:"createTime"`  // 创建时间
	UpdateBy       int64             `gorm:"column:update_by;type:int(255);comment:更新者" json:"updateBy"`                      // 更新者
	UpdateTime     core.Time         `gorm:"column:update_time;autoUpdateTime;type:datetime;comment:更新时间" json:"updateTime"`  // 更新时间
	DeleteTime     gorm.DeletedAt    `gorm:"column:delete_time;type:datetime;comment:删除时间" json:"deleteTime"`                 // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
