// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/super-sunshines/echo-server-core/core"

const TableNameSysLogLogin = "sys_log_login"

// SysLogLogin mapped from table <sys_log_login>
type SysLogLogin struct {
	ID              int64     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	LoginType       int64     `gorm:"column:login_type;type:int(2);comment:登录方式" json:"loginType"`                   // 登录方式
	RequestMethod   string    `gorm:"column:request_method;type:varchar(255);comment:请求方法" json:"requestMethod"`     // 请求方法
	UserAgent       string    `gorm:"column:user_agent;type:varchar(500);comment:信息" json:"userAgent"`               // 信息
	OperateName     string    `gorm:"column:operate_name;type:varchar(255);comment:操作人员" json:"operateName"`         // 操作人员
	Status          int64     `gorm:"column:status;type:int(1);comment:登录状态" json:"status"`                          // 登录状态
	Browser         string    `gorm:"column:browser;type:varchar(255);comment:浏览器类型" json:"browser"`                 // 浏览器类型
	Os              string    `gorm:"column:os;type:varchar(255);comment:操作系统" json:"os"`                            // 操作系统
	OperateIP       string    `gorm:"column:operate_ip;type:varchar(255);comment:请求IP" json:"operateIp"`             // 请求IP
	OperateLocation string    `gorm:"column:operate_location;type:varchar(255);comment:请求地点" json:"operateLocation"` // 请求地点
	Msg             string    `gorm:"column:msg;type:text;comment:错误信息" json:"msg"`                                  // 错误信息
	OperateTime     core.Time `gorm:"column:operate_time;type:datetime;comment:操作时间" json:"operateTime"`             // 操作时间
}

// TableName SysLogLogin's table name
func (*SysLogLogin) TableName() string {
	return TableNameSysLogLogin
}
