// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/super-sunshines/echo-server-core/vben/gorm/model"
)

func newSysLoginInfo(db *gorm.DB, opts ...gen.DOOption) sysLoginInfo {
	_sysLoginInfo := sysLoginInfo{}

	_sysLoginInfo.sysLoginInfoDo.UseDB(db, opts...)
	_sysLoginInfo.sysLoginInfoDo.UseModel(&model.SysLoginInfo{})

	tableName := _sysLoginInfo.sysLoginInfoDo.TableName()
	_sysLoginInfo.ALL = field.NewAsterisk(tableName)
	_sysLoginInfo.ID = field.NewInt64(tableName, "id")
	_sysLoginInfo.LoginType = field.NewInt64(tableName, "login_type")
	_sysLoginInfo.RequestMethod = field.NewString(tableName, "request_method")
	_sysLoginInfo.UserAgent = field.NewString(tableName, "user_agent")
	_sysLoginInfo.OperateName = field.NewString(tableName, "operate_name")
	_sysLoginInfo.Status = field.NewInt64(tableName, "status")
	_sysLoginInfo.Browser = field.NewString(tableName, "browser")
	_sysLoginInfo.Os = field.NewString(tableName, "os")
	_sysLoginInfo.OperateIP = field.NewString(tableName, "operate_ip")
	_sysLoginInfo.OperateLocation = field.NewString(tableName, "operate_location")
	_sysLoginInfo.Msg = field.NewString(tableName, "msg")
	_sysLoginInfo.OperateTime = field.NewField(tableName, "operate_time")

	_sysLoginInfo.fillFieldMap()

	return _sysLoginInfo
}

type sysLoginInfo struct {
	sysLoginInfoDo

	ALL             field.Asterisk
	ID              field.Int64  // 主键
	LoginType       field.Int64  // 登录方式
	RequestMethod   field.String // 请求方法
	UserAgent       field.String // 信息
	OperateName     field.String // 操作人员
	Status          field.Int64  // 登录状态
	Browser         field.String // 浏览器类型
	Os              field.String // 操作系统
	OperateIP       field.String // 请求IP
	OperateLocation field.String // 请求地点
	Msg             field.String // 错误信息
	OperateTime     field.Field  // 操作时间

	fieldMap map[string]field.Expr
}

func (s sysLoginInfo) Table(newTableName string) *sysLoginInfo {
	s.sysLoginInfoDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLoginInfo) As(alias string) *sysLoginInfo {
	s.sysLoginInfoDo.DO = *(s.sysLoginInfoDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLoginInfo) updateTableName(table string) *sysLoginInfo {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.LoginType = field.NewInt64(table, "login_type")
	s.RequestMethod = field.NewString(table, "request_method")
	s.UserAgent = field.NewString(table, "user_agent")
	s.OperateName = field.NewString(table, "operate_name")
	s.Status = field.NewInt64(table, "status")
	s.Browser = field.NewString(table, "browser")
	s.Os = field.NewString(table, "os")
	s.OperateIP = field.NewString(table, "operate_ip")
	s.OperateLocation = field.NewString(table, "operate_location")
	s.Msg = field.NewString(table, "msg")
	s.OperateTime = field.NewField(table, "operate_time")

	s.fillFieldMap()

	return s
}

func (s *sysLoginInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLoginInfo) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["login_type"] = s.LoginType
	s.fieldMap["request_method"] = s.RequestMethod
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["operate_name"] = s.OperateName
	s.fieldMap["status"] = s.Status
	s.fieldMap["browser"] = s.Browser
	s.fieldMap["os"] = s.Os
	s.fieldMap["operate_ip"] = s.OperateIP
	s.fieldMap["operate_location"] = s.OperateLocation
	s.fieldMap["msg"] = s.Msg
	s.fieldMap["operate_time"] = s.OperateTime
}

func (s sysLoginInfo) clone(db *gorm.DB) sysLoginInfo {
	s.sysLoginInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysLoginInfo) replaceDB(db *gorm.DB) sysLoginInfo {
	s.sysLoginInfoDo.ReplaceDB(db)
	return s
}

type sysLoginInfoDo struct{ gen.DO }

type ISysLoginInfoDo interface {
	gen.SubQuery
	Debug() ISysLoginInfoDo
	WithContext(ctx context.Context) ISysLoginInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLoginInfoDo
	WriteDB() ISysLoginInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLoginInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLoginInfoDo
	Not(conds ...gen.Condition) ISysLoginInfoDo
	Or(conds ...gen.Condition) ISysLoginInfoDo
	Select(conds ...field.Expr) ISysLoginInfoDo
	Where(conds ...gen.Condition) ISysLoginInfoDo
	Order(conds ...field.Expr) ISysLoginInfoDo
	Distinct(cols ...field.Expr) ISysLoginInfoDo
	Omit(cols ...field.Expr) ISysLoginInfoDo
	Join(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo
	Group(cols ...field.Expr) ISysLoginInfoDo
	Having(conds ...gen.Condition) ISysLoginInfoDo
	Limit(limit int) ISysLoginInfoDo
	Offset(offset int) ISysLoginInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLoginInfoDo
	Unscoped() ISysLoginInfoDo
	Create(values ...*model.SysLoginInfo) error
	CreateInBatches(values []*model.SysLoginInfo, batchSize int) error
	Save(values ...*model.SysLoginInfo) error
	First() (*model.SysLoginInfo, error)
	Take() (*model.SysLoginInfo, error)
	Last() (*model.SysLoginInfo, error)
	Find() ([]*model.SysLoginInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysLoginInfo, err error)
	FindInBatches(result *[]*model.SysLoginInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysLoginInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLoginInfoDo
	Assign(attrs ...field.AssignExpr) ISysLoginInfoDo
	Joins(fields ...field.RelationField) ISysLoginInfoDo
	Preload(fields ...field.RelationField) ISysLoginInfoDo
	FirstOrInit() (*model.SysLoginInfo, error)
	FirstOrCreate() (*model.SysLoginInfo, error)
	FindByPage(offset int, limit int) (result []*model.SysLoginInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLoginInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLoginInfoDo) Debug() ISysLoginInfoDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLoginInfoDo) WithContext(ctx context.Context) ISysLoginInfoDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLoginInfoDo) ReadDB() ISysLoginInfoDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLoginInfoDo) WriteDB() ISysLoginInfoDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLoginInfoDo) Session(config *gorm.Session) ISysLoginInfoDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLoginInfoDo) Clauses(conds ...clause.Expression) ISysLoginInfoDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLoginInfoDo) Returning(value interface{}, columns ...string) ISysLoginInfoDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLoginInfoDo) Not(conds ...gen.Condition) ISysLoginInfoDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLoginInfoDo) Or(conds ...gen.Condition) ISysLoginInfoDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLoginInfoDo) Select(conds ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLoginInfoDo) Where(conds ...gen.Condition) ISysLoginInfoDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLoginInfoDo) Order(conds ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLoginInfoDo) Distinct(cols ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLoginInfoDo) Omit(cols ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLoginInfoDo) Join(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLoginInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLoginInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLoginInfoDo) Group(cols ...field.Expr) ISysLoginInfoDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLoginInfoDo) Having(conds ...gen.Condition) ISysLoginInfoDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLoginInfoDo) Limit(limit int) ISysLoginInfoDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLoginInfoDo) Offset(offset int) ISysLoginInfoDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLoginInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLoginInfoDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLoginInfoDo) Unscoped() ISysLoginInfoDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLoginInfoDo) Create(values ...*model.SysLoginInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLoginInfoDo) CreateInBatches(values []*model.SysLoginInfo, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLoginInfoDo) Save(values ...*model.SysLoginInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLoginInfoDo) First() (*model.SysLoginInfo, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginInfo), nil
	}
}

func (s sysLoginInfoDo) Take() (*model.SysLoginInfo, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginInfo), nil
	}
}

func (s sysLoginInfoDo) Last() (*model.SysLoginInfo, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginInfo), nil
	}
}

func (s sysLoginInfoDo) Find() ([]*model.SysLoginInfo, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysLoginInfo), err
}

func (s sysLoginInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysLoginInfo, err error) {
	buf := make([]*model.SysLoginInfo, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLoginInfoDo) FindInBatches(result *[]*model.SysLoginInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLoginInfoDo) Attrs(attrs ...field.AssignExpr) ISysLoginInfoDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLoginInfoDo) Assign(attrs ...field.AssignExpr) ISysLoginInfoDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLoginInfoDo) Joins(fields ...field.RelationField) ISysLoginInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLoginInfoDo) Preload(fields ...field.RelationField) ISysLoginInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLoginInfoDo) FirstOrInit() (*model.SysLoginInfo, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginInfo), nil
	}
}

func (s sysLoginInfoDo) FirstOrCreate() (*model.SysLoginInfo, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginInfo), nil
	}
}

func (s sysLoginInfoDo) FindByPage(offset int, limit int) (result []*model.SysLoginInfo, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLoginInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLoginInfoDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLoginInfoDo) Delete(models ...*model.SysLoginInfo) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLoginInfoDo) withDO(do gen.Dao) *sysLoginInfoDo {
	s.DO = *do.(*gen.DO)
	return s
}
