// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/super-sunshines/echo-server-core/vben/gorm/model"
)

func newSysLogOperate(db *gorm.DB, opts ...gen.DOOption) sysLogOperate {
	_sysLogOperate := sysLogOperate{}

	_sysLogOperate.sysLogOperateDo.UseDB(db, opts...)
	_sysLogOperate.sysLogOperateDo.UseModel(&model.SysLogOperate{})

	tableName := _sysLogOperate.sysLogOperateDo.TableName()
	_sysLogOperate.ALL = field.NewAsterisk(tableName)
	_sysLogOperate.ID = field.NewInt64(tableName, "id")
	_sysLogOperate.Title = field.NewString(tableName, "title")
	_sysLogOperate.BusinessType = field.NewInt64(tableName, "business_type")
	_sysLogOperate.CallFunc = field.NewString(tableName, "call_func")
	_sysLogOperate.RequestMethod = field.NewString(tableName, "request_method")
	_sysLogOperate.OperateUserID = field.NewInt64(tableName, "operate_user_id")
	_sysLogOperate.OperateType = field.NewInt64(tableName, "operate_type")
	_sysLogOperate.OperateName = field.NewString(tableName, "operate_name")
	_sysLogOperate.OperateDepart = field.NewString(tableName, "operate_depart")
	_sysLogOperate.OperateURL = field.NewString(tableName, "operate_url")
	_sysLogOperate.OperateIP = field.NewString(tableName, "operate_ip")
	_sysLogOperate.OperateLocation = field.NewString(tableName, "operate_location")
	_sysLogOperate.OperateParam = field.NewString(tableName, "operate_param")
	_sysLogOperate.RequestJSONBody = field.NewString(tableName, "request_json_body")
	_sysLogOperate.JSONResult = field.NewString(tableName, "json_result")
	_sysLogOperate.ErrorMsg = field.NewString(tableName, "error_msg")
	_sysLogOperate.Status = field.NewInt64(tableName, "status")
	_sysLogOperate.OperateTime = field.NewField(tableName, "operate_time")
	_sysLogOperate.CostTime = field.NewInt64(tableName, "cost_time")

	_sysLogOperate.fillFieldMap()

	return _sysLogOperate
}

type sysLogOperate struct {
	sysLogOperateDo

	ALL             field.Asterisk
	ID              field.Int64  // 主键
	Title           field.String // 标题
	BusinessType    field.Int64  // 业务类型
	CallFunc        field.String // 执行的方法
	RequestMethod   field.String // 请求方法
	OperateUserID   field.Int64  // 操作者ID
	OperateType     field.Int64  // 操作类型
	OperateName     field.String // 操作人员
	OperateDepart   field.String // 部门名称
	OperateURL      field.String // 请求地址
	OperateIP       field.String // 请求IP
	OperateLocation field.String // 请求地点
	OperateParam    field.String // 请求参数
	RequestJSONBody field.String // 请求体
	JSONResult      field.String // 返回响应
	ErrorMsg        field.String // 错误信息
	Status          field.Int64  // 操作状态
	OperateTime     field.Field  // 操作时间
	CostTime        field.Int64  // 消耗时间

	fieldMap map[string]field.Expr
}

func (s sysLogOperate) Table(newTableName string) *sysLogOperate {
	s.sysLogOperateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLogOperate) As(alias string) *sysLogOperate {
	s.sysLogOperateDo.DO = *(s.sysLogOperateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLogOperate) updateTableName(table string) *sysLogOperate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Title = field.NewString(table, "title")
	s.BusinessType = field.NewInt64(table, "business_type")
	s.CallFunc = field.NewString(table, "call_func")
	s.RequestMethod = field.NewString(table, "request_method")
	s.OperateUserID = field.NewInt64(table, "operate_user_id")
	s.OperateType = field.NewInt64(table, "operate_type")
	s.OperateName = field.NewString(table, "operate_name")
	s.OperateDepart = field.NewString(table, "operate_depart")
	s.OperateURL = field.NewString(table, "operate_url")
	s.OperateIP = field.NewString(table, "operate_ip")
	s.OperateLocation = field.NewString(table, "operate_location")
	s.OperateParam = field.NewString(table, "operate_param")
	s.RequestJSONBody = field.NewString(table, "request_json_body")
	s.JSONResult = field.NewString(table, "json_result")
	s.ErrorMsg = field.NewString(table, "error_msg")
	s.Status = field.NewInt64(table, "status")
	s.OperateTime = field.NewField(table, "operate_time")
	s.CostTime = field.NewInt64(table, "cost_time")

	s.fillFieldMap()

	return s
}

func (s *sysLogOperate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLogOperate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["title"] = s.Title
	s.fieldMap["business_type"] = s.BusinessType
	s.fieldMap["call_func"] = s.CallFunc
	s.fieldMap["request_method"] = s.RequestMethod
	s.fieldMap["operate_user_id"] = s.OperateUserID
	s.fieldMap["operate_type"] = s.OperateType
	s.fieldMap["operate_name"] = s.OperateName
	s.fieldMap["operate_depart"] = s.OperateDepart
	s.fieldMap["operate_url"] = s.OperateURL
	s.fieldMap["operate_ip"] = s.OperateIP
	s.fieldMap["operate_location"] = s.OperateLocation
	s.fieldMap["operate_param"] = s.OperateParam
	s.fieldMap["request_json_body"] = s.RequestJSONBody
	s.fieldMap["json_result"] = s.JSONResult
	s.fieldMap["error_msg"] = s.ErrorMsg
	s.fieldMap["status"] = s.Status
	s.fieldMap["operate_time"] = s.OperateTime
	s.fieldMap["cost_time"] = s.CostTime
}

func (s sysLogOperate) clone(db *gorm.DB) sysLogOperate {
	s.sysLogOperateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysLogOperate) replaceDB(db *gorm.DB) sysLogOperate {
	s.sysLogOperateDo.ReplaceDB(db)
	return s
}

type sysLogOperateDo struct{ gen.DO }

type ISysLogOperateDo interface {
	gen.SubQuery
	Debug() ISysLogOperateDo
	WithContext(ctx context.Context) ISysLogOperateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLogOperateDo
	WriteDB() ISysLogOperateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLogOperateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLogOperateDo
	Not(conds ...gen.Condition) ISysLogOperateDo
	Or(conds ...gen.Condition) ISysLogOperateDo
	Select(conds ...field.Expr) ISysLogOperateDo
	Where(conds ...gen.Condition) ISysLogOperateDo
	Order(conds ...field.Expr) ISysLogOperateDo
	Distinct(cols ...field.Expr) ISysLogOperateDo
	Omit(cols ...field.Expr) ISysLogOperateDo
	Join(table schema.Tabler, on ...field.Expr) ISysLogOperateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLogOperateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLogOperateDo
	Group(cols ...field.Expr) ISysLogOperateDo
	Having(conds ...gen.Condition) ISysLogOperateDo
	Limit(limit int) ISysLogOperateDo
	Offset(offset int) ISysLogOperateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLogOperateDo
	Unscoped() ISysLogOperateDo
	Create(values ...*model.SysLogOperate) error
	CreateInBatches(values []*model.SysLogOperate, batchSize int) error
	Save(values ...*model.SysLogOperate) error
	First() (*model.SysLogOperate, error)
	Take() (*model.SysLogOperate, error)
	Last() (*model.SysLogOperate, error)
	Find() ([]*model.SysLogOperate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysLogOperate, err error)
	FindInBatches(result *[]*model.SysLogOperate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysLogOperate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLogOperateDo
	Assign(attrs ...field.AssignExpr) ISysLogOperateDo
	Joins(fields ...field.RelationField) ISysLogOperateDo
	Preload(fields ...field.RelationField) ISysLogOperateDo
	FirstOrInit() (*model.SysLogOperate, error)
	FirstOrCreate() (*model.SysLogOperate, error)
	FindByPage(offset int, limit int) (result []*model.SysLogOperate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLogOperateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLogOperateDo) Debug() ISysLogOperateDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLogOperateDo) WithContext(ctx context.Context) ISysLogOperateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLogOperateDo) ReadDB() ISysLogOperateDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLogOperateDo) WriteDB() ISysLogOperateDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLogOperateDo) Session(config *gorm.Session) ISysLogOperateDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLogOperateDo) Clauses(conds ...clause.Expression) ISysLogOperateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLogOperateDo) Returning(value interface{}, columns ...string) ISysLogOperateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLogOperateDo) Not(conds ...gen.Condition) ISysLogOperateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLogOperateDo) Or(conds ...gen.Condition) ISysLogOperateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLogOperateDo) Select(conds ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLogOperateDo) Where(conds ...gen.Condition) ISysLogOperateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLogOperateDo) Order(conds ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLogOperateDo) Distinct(cols ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLogOperateDo) Omit(cols ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLogOperateDo) Join(table schema.Tabler, on ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLogOperateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLogOperateDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLogOperateDo) Group(cols ...field.Expr) ISysLogOperateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLogOperateDo) Having(conds ...gen.Condition) ISysLogOperateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLogOperateDo) Limit(limit int) ISysLogOperateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLogOperateDo) Offset(offset int) ISysLogOperateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLogOperateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLogOperateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLogOperateDo) Unscoped() ISysLogOperateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLogOperateDo) Create(values ...*model.SysLogOperate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLogOperateDo) CreateInBatches(values []*model.SysLogOperate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLogOperateDo) Save(values ...*model.SysLogOperate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLogOperateDo) First() (*model.SysLogOperate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLogOperate), nil
	}
}

func (s sysLogOperateDo) Take() (*model.SysLogOperate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLogOperate), nil
	}
}

func (s sysLogOperateDo) Last() (*model.SysLogOperate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLogOperate), nil
	}
}

func (s sysLogOperateDo) Find() ([]*model.SysLogOperate, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysLogOperate), err
}

func (s sysLogOperateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysLogOperate, err error) {
	buf := make([]*model.SysLogOperate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLogOperateDo) FindInBatches(result *[]*model.SysLogOperate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLogOperateDo) Attrs(attrs ...field.AssignExpr) ISysLogOperateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLogOperateDo) Assign(attrs ...field.AssignExpr) ISysLogOperateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLogOperateDo) Joins(fields ...field.RelationField) ISysLogOperateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLogOperateDo) Preload(fields ...field.RelationField) ISysLogOperateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLogOperateDo) FirstOrInit() (*model.SysLogOperate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLogOperate), nil
	}
}

func (s sysLogOperateDo) FirstOrCreate() (*model.SysLogOperate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLogOperate), nil
	}
}

func (s sysLogOperateDo) FindByPage(offset int, limit int) (result []*model.SysLogOperate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLogOperateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLogOperateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLogOperateDo) Delete(models ...*model.SysLogOperate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLogOperateDo) withDO(do gen.Dao) *sysLogOperateDo {
	s.DO = *do.(*gen.DO)
	return s
}
